{% set name = "ugrid-checks" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 31dfba5753f0152301b3caf0e1c1955eef2a1c6b64a6ee6720fcd7396d232688

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - ugrid-checker = ugrid_checks.cli:call_cli

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools >=45
  run:
    - python >=3.7
    - netCDF4

test:
  imports:
    - ugrid_checks
  commands:
    - ugrid-checker --help

about:
  home: https://github.com/pp-mo/ugrid-checks
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A utility to check NetCDF files to the UGRID specification
  description: A utility to check NetCDF files to the UGRID specification

extra:
  recipe-maintainers:
    - pp-mo
    - bjlittle
