{% set name = "ugrid-checks" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ef87be311794c664f7d505c7ace20ffffd32078f8098f5f981320351ab5a1040

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - ugrid-checker = ugrid_checks.cli:call_cli

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=45
  run:
    - python >={{ python_min }}
    - netCDF4

test:
  requires:
    - python {{ python_min }}
  imports:
    - ugrid_checks
  commands:
    - ugrid-checker --help

about:
  home: https://github.com/pp-mo/ugrid-checks
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A utility to check NetCDF files to the UGRID specification
  description: A utility to check NetCDF files to the UGRID specification

extra:
  recipe-maintainers:
    - pp-mo
    - bjlittle
